#Get file
GET http://localhost:3335/api/files/65b3b82a32c5253045bcda13
###

#Upload file
POST http://localhost:3335/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="testPhoto"

<C:\Users\alien\Downloads\j2xS3_9sazQ.jpg
--boundary--

###
