POST http://localhost:4000/api/posts/51bd7639-adc1-49c6-8fc1-be98969f0c7e/likes/like HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJlOTg4YTIxYTdhMTVhMTQ4ZWMzZjEiLCJlbWFpbCI6Imdob3N0QG1vcnR5LmNvbSIsIm5hbWUiOiJHaG9zdFJpZGVyIiwiYXZhdGFyVXJsIjoidXBsb2Fkcy9hdmF0YXJzLzEyMyIsImlhdCI6MTcwNjk5MDExMywiZXhwIjoxNzA2OTkwNDEzfQ.qeks96qcwbnCg5ZAU9nWtWJW4xSQWzZaY4RzlYEyzio
###

POST http://localhost:4000/api/posts/51bd7639-adc1-49c6-8fc1-be98969f0c7e/likes/dislike HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJlOTg4YTIxYTdhMTVhMTQ4ZWMzZjEiLCJlbWFpbCI6Imdob3N0QG1vcnR5LmNvbSIsIm5hbWUiOiJHaG9zdFJpZGVyIiwiYXZhdGFyVXJsIjoidXBsb2Fkcy9hdmF0YXJzLzEyMyIsImlhdCI6MTcwNjk5MDExMywiZXhwIjoxNzA2OTkwNDEzfQ.qeks96qcwbnCg5ZAU9nWtWJW4xSQWzZaY4RzlYEyzio
###

#Get all comments by post
GET http://localhost:4000/api/posts/51bd7639-adc1-49c6-8fc1-be98969f0c7e/comments/ HTTP/1.1

###
