POST http://localhost:4000/api/posts/51bd7639-adc1-49c6-8fc1-be98969f0c7e/likes/like HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJlOTg4YTIxYTdhMTVhMTQ4ZWMzZjEiLCJlbWFpbCI6Imdob3N0QG1vcnR5LmNvbSIsIm5hbWUiOiJHaG9zdFJpZGVyIiwiYXZhdGFyVXJsIjoidXBsb2Fkcy9hdmF0YXJzLzEyMyIsImlhdCI6MTcwNzA2NDczNiwiZXhwIjoxNzA3MDY1MDM2fQ.MzvyRJW9PVKzv9adFOyg7Eb4_H7gRHqj37oNzfyD5MY

###

POST http://localhost:4000/api/posts/51bd7639-adc1-49c6-8fc1-be98969f0c7e/likes/dislike HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJlOTg4YTIxYTdhMTVhMTQ4ZWMzZjEiLCJlbWFpbCI6Imdob3N0QG1vcnR5LmNvbSIsIm5hbWUiOiJHaG9zdFJpZGVyIiwiYXZhdGFyVXJsIjoidXBsb2Fkcy9hdmF0YXJzLzEyMyIsImlhdCI6MTcwNzA2NTEzNSwiZXhwIjoxNzA3MDY1NDM1fQ.nKbze9Ijn5apX_7IJdIGOUc_hGSHXLxSYAdRr4I67fo
###

#Get all comments by post
GET http://localhost:4000/api/posts/51bd7639-adc1-49c6-8fc1-be98969f0c7e/comments/ HTTP/1.1

###
