#Create new user
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "AkiraRacer",
  "password": "motorbike",
  "avatarUrl": "uploads/avatars/racer",
  "email": "wroom@bike.com"
}
###

#Authorize user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "wroom@bike.com",
  "password": "coolSecret"
}
###

#Refresh access/refresh tokens
POST http://localhost:4546/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI5YmRjYmE3MTE0OTBjNDA4YWMzZDYiLCJlbWFpbCI6Indyb29tQGJpa2UuY29tIiwibmFtZSI6IkFraXJhUmFjZXIiLCJhdmF0YXJVcmwiOiJ1cGxvYWRzL2F2YXRhcnMvcmFjZXIiLCJ0b2tlbklkIjoiY2NhMDI0ODctYmE2ZS00MTI5LWI2MDQtZjZhNjg3M2ZjYzEzIiwiaWF0IjoxNzA3MDY5MjU5LCJleHAiOjE3MDk2NjEyNTl9.ik4Ns4O8QGIM-y9U9ZzFurTh44Z4Oa1CZEty58XfIMU
###

#Get user by id
GET http://localhost:4546/api/auth/65b9b8eec998deaad5595af0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI5YmRjYmE3MTE0OTBjNDA4YWMzZDYiLCJlbWFpbCI6Indyb29tQGJpa2UuY29tIiwibmFtZSI6IkFraXJhUmFjZXIiLCJhdmF0YXJVcmwiOiJ1cGxvYWRzL2F2YXRhcnMvcmFjZXIiLCJpYXQiOjE3MDY5ODMwMjYsImV4cCI6MTcwNjk4MzMyNn0.zoe7Wfnud_2v1HBAY63veOw-tdG5VhHq1BRmlKh6ASQ
###

#Change user password
PATCH http://localhost:4546/api/auth/65b9bdcba711490c408ac3d6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI5YmRjYmE3MTE0OTBjNDA4YWMzZDYiLCJlbWFpbCI6Indyb29tQGJpa2UuY29tIiwibmFtZSI6IkFraXJhUmFjZXIiLCJhdmF0YXJVcmwiOiJ1cGxvYWRzL2F2YXRhcnMvcmFjZXIiLCJpYXQiOjE3MDY5ODMwMjYsImV4cCI6MTcwNjk4MzMyNn0.zoe7Wfnud_2v1HBAY63veOw-tdG5VhHq1BRmlKh6ASQ
Content-Type: application/json

{
  "oldPassword": "iAmAkira",
  "newPassword": "coolSecret"
}
###

#Get file
GET http://localhost:3000/api/files/65b9d6c5c0786e923689ac98
###

#Upload file
POST http://localhost:3000/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="testPhoto"

<C:\Users\alien\Downloads\j2xS3_9sazQ.jpg
--boundary--
###

#Get post by Title
POST http://localhost:3000/api/posts/title HTTP/1.1
Content-Type: application/json

{
  "queryString": "Мин"
}
###

#Get all posts
GET http://localhost:3000/api/posts/ HTTP/1.1
###

#Get post by id
GET http://localhost:3000/api/posts/12ba7b55-ee20-4c53-8d0f-b5179f2975d5 HTTP/1.1
###

#Create new Post
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json

{
  "userId": "65a315542e79f6c6a9a4bfac",
  "postType": "text",
  "title": "Минasdaasasdasdadasdasdasdasdasdasdsadasd ",
  "announcement": "Текст с анонсом публикации. Минимальная длина 50 символов, максимальная 255.",
  "postText": "Текст публикации (обязательно). Минимальная длина 100 символов, максимальная 1024 символа. Минимальная длина 100",
  "tags": ["a2ac020c-bb62-4564-81b2-3dde62f2d118", "3f00cb99-cc9d-4c53-b784-6da39cedf9ce"]
}

###

#Update post by ID
PATCH http://localhost:3000/api/posts/59d5d02c-3247-4395-95f9-1ccda3a08bbf HTTP/1.1
Content-Type: application/json

{
  "announcement": "Минимальная длина 50 символов, максимальная 255. Текст с анонсом публикации."
}
###

#Delete post by ID
DELETE http://localhost:3000/api/posts/12ba7b55-ee20-4c53-8d0f-b5179f2975d5 HTTP/1.1
###

#Add like on post
POST http://localhost:3000/api/posts/12ba7b55-ee20-4c53-8d0f-b5179f2975d5/likes/like HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI5YmRjYmE3MTE0OTBjNDA4YWMzZDYiLCJlbWFpbCI6Indyb29tQGJpa2UuY29tIiwibmFtZSI6IkFraXJhUmFjZXIiLCJhdmF0YXJVcmwiOiJ1cGxvYWRzL2F2YXRhcnMvcmFjZXIiLCJpYXQiOjE3MDcwNjg1NzksImV4cCI6MTcwNzA2ODg3OX0.YXWTGAC9Ij-1Kf08Z81fOA_csyZC9PJR8i9e0ryyQmE
###

#Delete like from post
DELETE http://localhost:3000/api/posts/12ba7b55-ee20-4c53-8d0f-b5179f2975d5/likes/dislike HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWI5YmRjYmE3MTE0OTBjNDA4YWMzZDYiLCJlbWFpbCI6Indyb29tQGJpa2UuY29tIiwibmFtZSI6IkFraXJhUmFjZXIiLCJhdmF0YXJVcmwiOiJ1cGxvYWRzL2F2YXRhcnMvcmFjZXIiLCJpYXQiOjE3MDcwNjg1NzksImV4cCI6MTcwNzA2ODg3OX0.YXWTGAC9Ij-1Kf08Z81fOA_csyZC9PJR8i9e0ryyQmE
###

#Publish post by ID
PATCH  http://localhost:3000/api/posts/1c711844-dcd4-4a0b-af31-2eda29ab56ec/publish HTTP/1.1
###
